### ISSUE TITLE
How to bypass the proceed promt?

### ISSUE THREAD

**Issue by kdmsit** [mohanliu/qmpy_rester#8]

**Comment by kdmsit** [comment]
Whenever I am running the code 
     with qr.QMPYRester() as q:
        kwargs = {
            "composition": 'WCl4'
            # "composition": composition
            }

It is showing 
Your filters are:
    composition=WCl4
Proceed? [Y/n]:

and I have to give Y. Cant we bypass this with default Y as input?

**Comment by mohanliu** [comment]
Just add `"verbose": False` into your `kwargs` dictionary.

**Comment by kdmsit** [comment]
Issue got resloved
